"""Changed city name constraints

Revision ID: 844b7243b574
Revises: 98eb341dfcee
Create Date: 2026-01-27 19:19:29.425064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844b7243b574'
down_revision: Union[str, Sequence[str], None] = '98eb341dfcee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_city_name'), table_name='city')
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_city_name'), table_name='city')
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=1)
    # ### end Alembic commands ###
